name: Tests LibSQL

on:
  push:
    branches:
      - main

jobs:
  unit:
    strategy:
      matrix:
        go-version:
          - 1.23.x
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ matrix.go-version }}"
      - run: go test -v
